name:                mockcat
version:             0.1.0.0
github:              pujoheadsoft/mockcat
license:             "MIT"
author:              "funnycat <pujoheadsoft@gmail.com>"
maintainer:          "funnycat <pujoheadsoft@gmail.com>"
copyright:           "2024 funnycat"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mockcat#readme>

dependencies:
- base >= 4.7 && < 5
- text
- template-haskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  mockcat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mockcat
    - hspec
