name:                mockcat
version:             0.5.5.0
github:              pujoheadsoft/mockcat
license:             "MIT"
author:              "funnycat <pujoheadsoft@gmail.com>"
maintainer:          "funnycat <pujoheadsoft@gmail.com>"
copyright:           "2024 funnycat"

extra-source-files:
- README.md
- README-ja.md
- CHANGELOG.md

synopsis: Mock library for test in Haskell.

category: Testing

description: |
  mockcat is a small mocking / stubbing DSL for Haskell tests.

  Features:

  * Describe expectations with left-to-right pipelines: `arg |> ... |> result`
  * Generate typeclass mocks via Template Haskell (`makeMock`, `makePartialMock`)
  * Create standalone function stubs (`createStubFn`, constant mocks)
  * Flexible return behaviour: vary by argument or occurrence (including identical args later)
  * Optional per-call variation for `IO a` results
  * Concurrency-safe counting and explicit lazy semantics (unevaluated results are not recorded)
  * Simple verification helpers (apply count predicates, ordering checks)
  * Partial adoption: mock only selected methods; no hidden global state

  See README for full examples: <https://github.com/pujoheadsoft/mockcat#readme>

tested-with:
  - GHC == 9.2.8
  - GHC == 9.4.8
  - GHC == 9.6.3
  - GHC == 9.8.2
  - GHC == 9.10.1

dependencies:
- base >= 4.7 && < 5
- text >= 2.0 && < 2.2
- template-haskell >= 2.18 && < 2.24
- mtl >= 2.3.1 && < 2.4
- transformers >= 0.5.6 && < 0.7
- unliftio-core >= 0.2.1.0 && < 0.2.2
- unliftio >= 0.2.25.0 && < 0.2.26

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fprint-potential-instances
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  mockcat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
    - mockcat
    - hspec >= 2.11 && < 2.13
    - async >= 2.2.4 && < 2.3
    - QuickCheck >= 2.14 && < 2.17
    - hashable >= 1.4 && < 1.5
    - unordered-containers >= 0.2.19 && < 0.3