name:                mockcat
version:             0.2.0.0
github:              pujoheadsoft/mockcat
license:             "MIT"
author:              "funnycat <pujoheadsoft@gmail.com>"
maintainer:          "funnycat <pujoheadsoft@gmail.com>"
copyright:           "2024 funnycat"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis: Simple mock function library for test in Haskell.

category: Testing

description: |
  mockcat is simple mock library for test in Haskell.

  mockcat provides so-called stubbing and verification functions.

  Stub functions can return values of Pure Types as well as value of Monadic Types.

  Example:

  @
  f \<- createStubFn $ "expected arg" |\> "return value"
  print $ f "expected arg" -- "return value" 
  @
  
  For more please see the README on GitHub at <https://github.com/pujoheadsoft/mockcat#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 2.0 && < 2.2
- template-haskell >= 2.18 && < 2.23

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fprint-potential-instances

library:
  source-dirs: src

tests:
  mockcat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mockcat
    - hspec
