name:                mockcat
version:             0.5.2.0
github:              pujoheadsoft/mockcat
license:             "MIT"
author:              "funnycat <pujoheadsoft@gmail.com>"
maintainer:          "funnycat <pujoheadsoft@gmail.com>"
copyright:           "2024 funnycat"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis: Mock library for test in Haskell.

category: Testing

description: |
  mockcat is a flexible and powerful mock library.

  It provides the following main features.

  - Mock generation of monadic typeclasses

  - Generation of stub functions independent of typeclasses

  - Verification of stub functions

  Stub functions can return not only values of monadic types, but also pure types.
  
  For more please see the README on GitHub at <https://github.com/pujoheadsoft/mockcat#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 2.0 && < 2.2
- template-haskell >= 2.18 && < 2.23
- mtl >= 2.3.1 && < 2.4
- transformers >= 0.5.6 && < 0.7

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fprint-potential-instances

library:
  source-dirs: src

tests:
  mockcat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
    - mockcat
    - hspec
