name:                mockcat
version:             1.3.1.0
github:              pujoheadsoft/mockcat
license:             "MIT"
author:              "funnycat <pujoheadsoft@gmail.com>"
maintainer:          "funnycat <pujoheadsoft@gmail.com>"
copyright:           "2025 funnycat"

extra-source-files:
- README.md
- README-ja.md
- CHANGELOG.md

synopsis: Declarative mocking with a single arrow `~>`.

category: Testing

description: |
  Mockcat is a minimal, architecture-agnostic mocking library for Haskell.
  It enables declarative verification and intent-driven matching, allowing you to define function behavior and expectations without specific architectural dependencies.

  See README for full examples: <https://github.com/pujoheadsoft/mockcat#readme>

tested-with:
  - GHC == 9.2.8
  - GHC == 9.4.8
  - GHC == 9.6.3
  - GHC == 9.8.2
  - GHC == 9.10.1

dependencies:
- base >= 4.7 && < 5
- text >= 2.0 && < 2.2
- template-haskell >= 2.18 && < 2.24
- mtl >= 2.2.2 && < 2.4
- transformers >= 0.5.6 && < 0.7
- unliftio-core >= 0.2.1.0 && < 0.2.2
- unliftio >= 0.2.25.0 && < 0.2.26
- containers >= 0.6 && < 0.8
- stm >= 2.5 && < 2.6

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fprint-potential-instances
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  mockcat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
    - mockcat
    - hspec >= 2.11 && < 2.13
    - inspection-testing >= 0.4 && < 0.7
    - async >= 2.2.4 && < 2.3
    - QuickCheck >= 2.14 && < 2.17
    - hashable >= 1.4 && < 1.6
    - unordered-containers >= 0.2.19 && < 0.3