on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.2.8', '9.4.8']
        cabal: ['3.10.3.0', '3.12.1.0']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    name: Haskell GHC ${{ matrix.ghc }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Build
        run: |
          cabal update
          cabal build
      - name: Test
        run: cabal test